version: '3.8'

services:
  nginx:
    build: .
    image: my_nginx:1.0
    container_name: my_nginx_container
    volumes:
      - ./container_data:/data
    env_file:
      - .env
    ports:
      - "80:80"
  